### ISSUE TITLE
Drio "."-hack

### ISSUE THREAD

**Issue by glensc** [ngyuki-sandbox/php-xhprof-xhgui#1]
https://github.com/perftools/xhgui/issues/209 has been merged so the "."-hack is no longer needed

**Comment by ngyuki** [comment]
Thank you!

**Comment by ngyuki** [comment]
@glensc Thank you!

**Comment by glensc** [comment]
Appropriate would be to create PR to see what changes were made. Or if forgotten, then just link the commits.
